using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ClassSaver2.Generator;

namespace ClassSaver2
{
    [Generator]
    public class Main : IIncrementalGenerator
    {
        // name constants
        private const string DefineDatatypeFullName = "ClassSaver2.PredefinedDatatypes.DefineDatatypeAttribute";
        private const string SerializableAttributeFullName = "global::System.SerializableAttribute";
        private const string SerializeMethodName = "System.SerializableAttribute";
        private const string NonSerializedAttributeFullName = "global::System.NonSerializedAttribute";
        private const string NonSerializedMethodName = "System.NonSerializedAttribute";
        
        private static readonly SymbolDisplayFormat CanonicalTypeFormat = 
            SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
                SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions 
                & ~SymbolDisplayMiscellaneousOptions.UseSpecialTypes
            );
        
            
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
#if DEBUG
            if (!System.Diagnostics.Debugger.IsAttached)
            {
                System.Diagnostics.Debugger.Launch();
            }
#endif
            
            var predefinedHandlerDictProvider = FetchPredefinedClasses(context);
            var serializableClassesProvider = FetchSerializableClasses(context);
            
            // now merge the serialized classes into the dict
            var serializableTypeNamesProvider = serializableClassesProvider
                .Select((symbol, _) => symbol.ToDisplayString(CanonicalTypeFormat))
                .Collect();
            
            var handlersProvider = predefinedHandlerDictProvider
                .Combine(serializableTypeNamesProvider)
                .Select((tuple, _) =>
                {
                    var (predefined, serializableNames) = tuple;
            
                    var dict = new Dictionary<string, (string TypeFullName, bool HasReturnType)>(predefined);

                    // any [Serializable] type is handled directly by ClassSaver
                    foreach (var typeName in serializableNames)
                    {
                        dict[typeName] = ("global::ClassSaver2.ClassSaver", false);
                    }

                    return dict;
                });
            
            var data = serializableClassesProvider.Combine(handlersProvider);
            
            context.RegisterSourceOutput(data, (scp, values) =>
            {
                // get everything out
                INamedTypeSymbol targetClass = values.Left;
                Dictionary<string, (string TypeFullName, bool HasReturnType)> handlerDict = values.Right;
                
                scp.AddSource($"ClassSaver_{targetClass}.g.cs", GenerateScriptSource(scp, targetClass, handlerDict));
            });
        }

        private static string GenerateScriptSource(SourceProductionContext context, INamedTypeSymbol classSymbol,
            Dictionary<string, (string TypeFullName, bool HasReturnType)> handlerDict)
        {
            // check if there are 0 initial constructors or not
            bool valid = classSymbol.IsValueType; // structs always have an overload for 0 constructor
            
            if (!valid)
            {
                foreach (var constructor in classSymbol.InstanceConstructors)
                {
                    if (constructor.Parameters.IsEmpty
                        && (constructor.DeclaredAccessibility == Accessibility.Public ||
                            constructor.DeclaredAccessibility == Accessibility.Internal))
                    {
                        valid = true;
                    }
                }
            }
            
            if (classSymbol.IsAbstract) valid = false;

            if (!valid)
            {
                Location classLocation = classSymbol.Locations[0];
        
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.MissingParameterlessConstructorRule,
                    classLocation,
                    classSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)
                ));

                return string.Empty;
            }
            
            StringBuilder outputString = new StringBuilder();
            var classString = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            
            // first start segment
            outputString.Append($@"
/// auto generated script, any changes will be overwritten.
/// generated by ClassSaver2

using System;
using System.IO;

namespace ClassSaver2
{{
    public static partial class ClassSaver
    {{
        public static void Write(BinaryWriter writer, {classString} data)
        {{
            ");
            
            // write function
            Queue<(string VarName, string VarTypeFullName, string HandlerTypeName, bool HandlerHasReturnType)> varOrder = new Queue<(string VarName, string VarTypeFullName, string HandlerTypeName, bool HandlerHasReturnType)>();

            bool hasError = false;
            GetSerializableFields(classSymbol, (fieldSymbol) =>
            {
                // for every field, fetch type's name
                var varTypeName = fieldSymbol.Type.ToDisplayString(CanonicalTypeFormat);
                if (!handlerDict.TryGetValue(varTypeName, out var handlerData))
                {
                    Location fieldLocation = fieldSymbol.Locations[0];

                    context.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.UnsupportedFieldTypeRule,
                        fieldLocation,
                        fieldSymbol.Name,
                        classSymbol.Name,
                        fieldSymbol.Type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)
                    ));

                    hasError = true;
                }
                
                if (!hasError) varOrder.Enqueue((fieldSymbol.Name, varTypeName, handlerData.TypeFullName, handlerData.HasReturnType));
                if (!hasError) outputString.Append($@"{handlerData.TypeFullName}.Write(writer, data.{fieldSymbol.Name});
            ");
            });

            if (hasError)
            {
                return string.Empty;
            }
            
            // read function
            outputString.Append($@"
        }}
        
        public static void Read(BinaryReader reader, out {classString} output)
        {{
            output = new {classString}();
            
            ");

            while (varOrder.Count > 0)
            {
                var varData = varOrder.Dequeue();

                if (varData.HandlerHasReturnType)
                {
                    outputString.Append($@"output.{varData.VarName} = {varData.HandlerTypeName}.Read(reader);
            ");
                }
                else
                {
                    var count = varOrder.Count;
                    outputString.Append($@"{varData.HandlerTypeName}.Read(reader, out {varData.VarTypeFullName} temp_{count});
            output.{varData.VarName} = temp_{count};
            ");
                }
            }

            outputString.Append($@"
        }}
    }}
}}");
            
            return outputString.ToString();
        }
            
        // <type's full name, handler's full name>
        private static IncrementalValueProvider<Dictionary<string, (string TypeFullName, bool HasReturnType)>> FetchPredefinedClasses(IncrementalGeneratorInitializationContext context)
        {
            var data =
                context.SyntaxProvider.ForAttributeWithMetadataName(
                    DefineDatatypeFullName,
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => 
                    {
                        var handlerClassSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
                        var attr = ctx.Attributes[0];
                        var targetTypeSymbol = (ITypeSymbol)attr.ConstructorArguments[0].Value;
            
                        return (TargetType: targetTypeSymbol, HandlerClass: handlerClassSymbol);
                    }
                );

            var collected = data.Collect();
            
            var returnData = collected.Select((handlers, _) =>
            {
                var dict = new Dictionary<string, (string TypeFullName, bool HasReturnType)>();
                
                // add in prefills too
                dict["global::System.Int32"] = ("global::ClassSaver2.PredefinedDatatypes.HandleInt", true);
                dict["global::System.String"] = ("global::ClassSaver2.PredefinedDatatypes.HandleString", true);
                dict["global::System.Single"] = ("global::ClassSaver2.PredefinedDatatypes.HandleFloat", true);
                
                foreach (var h in handlers)
                {
                    dict[h.TargetType.ToDisplayString(CanonicalTypeFormat)] = (h.HandlerClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), true);
                }

                return dict;
            });
            
            return returnData;
        }

        private static IncrementalValuesProvider<INamedTypeSymbol> FetchSerializableClasses(
            IncrementalGeneratorInitializationContext context)
        {
            return 
                context.SyntaxProvider.ForAttributeWithMetadataName(
                    SerializeMethodName,
                    predicate: (node, _) => node is ClassDeclarationSyntax || node is StructDeclarationSyntax,
                    transform: (ctx, _) => 
                    {
                        
                        var handlerClassSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
            
                        return handlerClassSymbol;
                    }
                );
        }

        private static void GetSerializableFields(INamedTypeSymbol classSymbol, Action<IFieldSymbol> setter)
        {
            foreach (ISymbol member in classSymbol.GetMembers())
            {
                if (!(member is IFieldSymbol field)) continue; // only do this for fields

                if (field.IsStatic || field.IsConst || field.IsImplicitlyDeclared)
                    continue;

                bool serializable = field.DeclaredAccessibility == Accessibility.Public;
                var attributes = field.GetAttributes();

                // scan through all of attributes name
                foreach (var attr in attributes)
                {
                    if (attr.AttributeClass == null) continue;
                    
                    var attrName = attr.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    if (attrName == NonSerializedAttributeFullName)
                    {
                        serializable = false;
                        break;
                    }

                    if (attrName != SerializableAttributeFullName) continue;

                    serializable = true;
                    break;
                }

                if (serializable)
                {
                    setter.Invoke(field);
                }
            }
        }
    }
}